# Python slim + Firefox/Chrome headless ready
FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# System deps (Firefox ESR + fonts; Chrome is optional)
RUN apt-get update && apt-get install -y --no-install-recommends \
    firefox-esr \
    libgtk-3-0 libdbus-glib-1-2 libxt6 libx11-xcb1 libxcb-dri3-0 libxdamage1 libgbm1 \
    fonts-liberation fonts-dejavu-core ca-certificates curl gnupg \
 && rm -rf /var/lib/apt/lists/*

# (Optionnel) Installer Chromium à la place
# RUN apt-get update && apt-get install -y --no-install-recommends chromium && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app

# Vars par défaut
ENV SELENIUM_BROWSER=firefox \
    SELENIUM_HEADLESS=1 \
    ALLOWED_ORIGINS="http://localhost:5173,http://127.0.0.1:5173"

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
