app = "lavatools-api"
primary_region = "ams"

[build]
  dockerfile = "Dockerfile"

[env]
  # Uvicorn écoutera dessus (et le Dockerfile lira cette variable)
  PORT = "8080"
  ALLOWED_ORIGINS = "https://lavatools-web.fly.dev,http://localhost:5173,http://127.0.0.1:5173"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    soft_limit = 100
    hard_limit = 200

  [[http_service.checks]]
    interval = "10s"
    timeout = "5s"
    grace_period = "60s"
    method = "GET"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
