FROM python:3.11-slim
WORKDIR /app

# Paquets système nécessaires (curl/unzip utiles pour debug/télémétrie)
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates curl unzip \
 && rm -rf /var/lib/apt/lists/*

# Dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Code
COPY app ./app

# IMPORTANT: Fly enverra le trafic sur $PORT (fly.toml=8080)
EXPOSE 8080

# 🔑 Utilise la shell-form pour que ${PORT} soit interpolé par le shell
CMD sh -c 'uvicorn app.main:app --host 0.0.0.0 --port ${PORT:-8080}'
